#cloud-config
write_files:
- path: /etc/nixos/host.nix
  permissions: '0644'
  content: |
    { config, lib, pkgs, user, ... }: {
      users.users = {
        "nix" = {
          description = "nix";
          extraGroups = [ "wheel" "systemd-journal" ];
          initialPassword = "nixos";
          isNormalUser = true;
          # shell = pkgs.zsh;
        };
      };
      environment.systemPackages = with pkgs; [ vim ];
      # networking
      networking.useNetworkd = true;
      networking.useDHCP = true;
      systemd.services.NetworkManager-wait-online.enable = false;
      systemd.network.wait-online.enable = false;
      systemd.services.systemd-networkd.stopIfChanged = false;
      systemd.services.systemd-resolved.stopIfChanged = false;
    }
users:
  - default
  - name: terraform
    gecos: terraform
    group: terraform
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    ssh_import_id:
      - gh:jamesepatrick
    lock_passwd: false
runcmd:
  - curl https://raw.githubusercontent.com/elitak/nixos-infect/master/nixos-infect | PROVIDER=hetznercloud NIXOS_IMPORT=./host.nix NIX_CHANNEL=nixos-unstable bash 2>&1 | tee /tmp/infect.log
